package me.loogeh.Hype.Inventory;

public enum IFlag {
	DISABLE_CLICK,
	DISABLE_DRAG,
	DISABLE_CLICK_TOP_AND_BOTTOM,
	DISABLE_SHIFT_CLICK,
	DISABLE_RIGHT_CLICK,
	DISABLE_LEFT_CLICK,
	DISABLE_DOUBLE_CLICK;
}
