squads:
  nametag_change: true
  max_power: 14
  min_power: -3
  max_allies: 10
  max_enemies: -1
  max_members: -1
  max_land: 10
  max_trusted_allies: -1
  starting_power: 2
  starting_allies: 10
  starting_land: 2
  land_per_player: 1
  power_per_player: 1
  power_regeneration_time: 300000
  max_admin_power: 10000
  max_admin_land: 10000
  max_admin_allies: 10000
  max_admin_enemies: 0
  max_name_length: 10
  min_name_length: 3
  special_chars_allowed: false
  disallow_interact: 23,26,54,61,62,64,71,93,94,96,107
  allow_interact: 107
  allow_place: 37,38
  allow_break: 6,12,13,39,40,59,81,83,86,103,104,105,115,127
  use_home_anywhere: true
  home_cooldown: 180
  home_delay: 6
  disallowed_names: shops,nether,spawn,arena,safezone,warzone,wilderness
  fall_damage_in_safezone: false
  wand_id: 359
  all_interactable_blocks: 23,26,54,58,61,62,64,69,77,84,93,94,95,96,116,117,118,120,130,137,145,146,149,150,158,324,328,329,333,355,356,379,380,404
  trust_interactable_blocks: 58,61,64,69,71,77,96,107,167,324,330
  disable_fire_spread: true
  block_usage_pressure_plates: false
  can_claim_next_to: false
  max_bank_balance: 3500000
  hourly_bank_withdraw_limit: 80000
armour:
  leather_take_fall_damage: false
  leather_arrow_poison_time: 2
  leather_arrow_poison_amplifier: 2
  leather_arrow_repulse_force: 2.5
  leather_arrow_paralyzing_time: 2
  leather_arrow_paralyzing_amplifier: 4
  leather_leap_force: 1.1
  leather_leap_cooldown: 8
  iron_shockwave_cooldown: 16
  iron_shockwave_radius: 7
  iron_shockwave_force: -2.0
  iron_resist_time: 6
  iron_resist_cooldown: 24
  iron_resist_amplifier: 4
  chain_can_drown: false
  chain_disable_hunger: true
  chain_berserker_time: 3
  chain_berserker_amplifier: 1
  chain_berserker_cooldown: 20
  chain_proximity_heal_amount: 6
  chain_proximity_heal_radius: 5
  chain_proximity_heal_cooldown: 10
  chain_triple_shot_cooldown: 16
  gold_take_lava_fire_damage: false
  gold_rush_time: 5
  gold_rush_amplifier: 2
  gold_rush_cooldown: 16
  gold_dodge_force: 13.5
  gold_dodge_cooldown: 8
  diamond_stomp_time: 7
  diamond_stomp_amplifier: 4
  diamond_stomp_cooldown: 16
  diamond_stomp_radius: 5
  diamond_switch_cooldown: 12
item:
  lightning_sceptre_enabled: true
  lightning_sceptre: 293
  lightning_sceptre_cooldown: 12
  incendiary_axe_enabled: true
  incendiary_axe: 286
  incendiary_axe_time: 3
  crippling_axe_enabled: true
  crippling_axe: 279
  crippling_axe_time: 3
  crippling_axe_amplifier: 3
  web_grenade_enabled: true
  fire_grenade_enabled: true
moderation:
  moderator_max_mute_duration: 24.0
  moderator_max_ban_duration: 8.0
channels:
  can_have_special_chars: false
  max_members: -1
  max_channels_per_player: -1
  format: '&2%channel_name% &a%player_name% &2> &a%message%'
  max_name_length: 10
  min_name_length: 2
server:
  lock_reason:
  chat_cooldown: 800
  disable_brewing: true
  untag_time: 50
mysql:
  address: xxx.xxx.xx.xx:3306/database_name
  user: myusername
  pass: mypassword