name: Hype
version: 0.1
description: HypeMC v2 Plugin > Beta
main: me.loogeh.Hype.Main.Main
commands:
  chatchannel:
    description: ChatChannels base command
  chatchannels:
    description: ChatChannels base command
  cc:
    description: ChatChannels base command
  s:
    description: Squads base command
  squad:
    description: /s alias
  squads:
    description: /s alias
  sa:
    description: Squads base admin command
  ban:
    description: Ban players
  unban:
    description: Unban banned players
  mute:
    description: Mute players
  unmute:
    description: Unmute muted players
  kick:
    description: Kick a player
  server:
    description: Server commands
  permissions:
    description: Permissions commands
    aliases: [permission,perms,perm]
  chat:
    description: Chat commands
  say:
    description: Broadcast a message to the server
  money:
    description: Economy command
  economy:
    description: Economy command
  balance:
    description: Economy command
  entity:
    description: Entity commands
  p:
    description: Player commands
  player:
    description: Player commands
  tp:
    description: Teleport commands
    aliases: [teleport]
  warp:
    description: Warp commands
  message:
    description: Message commands
    aliases: [m,msg,whisper,tell]
  reply:
    description: Reply commands
    aliases: [r]
  adminmessage:
    description: Message all online staff
    aliases: [a,am]
  shops:
    description: Shops commands
  armour:
    description: Armour commands
  game:
    description: Game Commands
  give:
    description: Give commands
  g:
    description: Give commands
  animal:
    description: Animal commands
  debug: